### ISSUE TITLE
Testing the testbed

### ISSUE THREAD

**Issue by previtus** [eaplatanios/nel_framework#1]
Hi, this is Vitek from the NEL class.
When and what to test?

Cheers, VR

**Comment by asaparov** [comment]
Hi Vitek!
So I'm testing the simulation itself for the moment. Things that would be really helpful: (1) visualization, and (2) finishing up the python-C interface.

(1) If you've worked with visualization before, in either c/c++ or python, it would be helpful if you could work on that. I'm thinking we draw the currently existing patches (and patches that haven't been generated yet are just part of the background; either black or white). Then for each existing patch, we draw a grid. We can draw items as colored circles (with a black border) within each grid cell. Their color is determined by the item's color property. Then maybe we can have a way to color the grid cells based on their vision property or their scent property. For now, we can assume both scent and vision are three-dimensional vectors, and so we can treat them as RGB for the purpose of visualization.

(2) Since I've been mostly working on the C side, I haven't been updating the Python API as I make changes on the C side. I've been testing the simulator code in simulator_test.cpp, so you can take a look there to see how to initialize and run the simulator.

**Comment by asaparov** [comment]
Also, for the visualization, it would be cool to be able to animate it, with each time step that passes in the simulation. I'm wondering if matplotlib is capable of doing that, or maybe you know of something more appropriate?
