### ISSUE TITLE
Agent vision does not update after step

### ISSUE THREAD

**Issue by SharmisthaJat** [eaplatanios/nel_framework#4]
Hi, 

We noticed that the agent.vision() value does not change after making a move in the simulator using self.simulator.move(agent,ag_move,steps). Can you please check this and let us know. 

Do let us know if there is another way to retrieve the vision field value. 

- Thanks
Test1 team

**Comment by asaparov** [comment]
That's because there is nothing in its field of view. In the tests and examples, vision_range is set to 1, so in order for agent.vision() to change, an item needs to come within 1 tile of the agent. So it might take many steps for the agent to see an item in its field of view. I've just tested this and it seems to be working in the current version.
